gems:
  - bourbon
  - neat
  - octopress-autoprefixer

# Structure configuration
source: source
destination: build

assets:
  cachebust: soft

# Site settings
title: Urban Sign
description: Urban Sign - a national leader in architechtural sign fabrication. 

# Name of project on Github
baseurl: ""
url: "http://urbansigncompany.com"

# Build settings
markdown: kramdown

exclude: ['vendor']
