gems:
  - bourbon
  - neat
  - octopress-autoprefixer

# Structure configuration
source: source
destination: build

assets:
  cachebust: soft

# Site settings
title: Jekyll Starter
description: Prototyping starter kit for Jekyll

# Name of project on Github
baseurl: ""
url: "54.172.155.116"

# Build settings
markdown: kramdown

exclude: ['vendor']
